<a href="https://colab.research.google.com/github/Marcin19721205/Timeseries_Data_Processing_Basic/blob/main/InferentialDS1_extracted_NN1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#CaO content Inferential DS1
Working on Extracted Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

sns.set()
np.random.seed(42)
np.set_printoptions(precision=4, suppress=True)
sklearn.__version__

'1.6.1'

Read from Google Drive

In [27]:
from google.colab import files
import pandas as pd


uploaded = files.upload()


#df = pd.read_csv('df_clean_avg.csv', sep='\t')   # <-- plik oddzielany tabulatorem
df_raw = pd.read_csv('df_clean_avg.csv', sep=';')   # <-- plik oddzielany przecinkiem
print("Data loaded correctly!\n")
print(df_raw.head())

Saving df_clean_avg.csv to df_clean_avg (1).csv
Data loaded correctly!

            ChangeTime  LabUpdate Inferential_avg Inferential_med  \
0  2025-10-16 03:02:30         68       52,716789     51,08698835
1  2025-10-16 06:33:30         60     62,41755307     63,74654023
2  2025-10-16 08:32:30         31     44,39371878     46,67294865
3  2025-10-16 10:35:40         32     23,31702046     23,99194305
4  2025-10-16 12:45:30         31      20,6122777     21,00740895

     Ratio_avg    Ratio_med       pH_avg       pH_med   CMFlow_avg  \
0  0,380589473  0,380293399  9,113029238  9,113762856  52,38471108
1   0,35585871  0,356621683  9,092202058  9,092871666   62,5942022
2  0,342781166  0,342676342  9,090918157  9,092871666  45,91751767
3  0,357974786  0,357905269  9,116514277  9,113762856  24,13672841
4    0,3405839  0,338620573  9,017560911  9,018521309  21,07282445

    CMFlow_med     error_avg     error_med
0  51,07588959    -15,283211  -16,91301165
1  64,00079346   2,417553072   3,746540225
2  46,83626556   13,39371878   15,67294865
3  24,36791992  -8,682979535  -8,008056952
4  21,40418625   -10,3877223  -9,992591051

Podstawowe Informacje

In [28]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ChangeTime       66 non-null     object
 1   LabUpdate        66 non-null     int64
 2   Inferential_avg  66 non-null     object
 3   Inferential_med  66 non-null     object
 4   Ratio_avg        66 non-null     object
 5   Ratio_med        66 non-null     object
 6   pH_avg           66 non-null     object
 7   pH_med           66 non-null     object
 8   CMFlow_avg       66 non-null     object
 9   CMFlow_med       66 non-null     object
 10  error_avg        66 non-null     object
 11  error_med        66 non-null     object
dtypes: int64(1), object(11)
memory usage: 6.3+ KB

In [29]:
dataset = df_raw.copy()
dataset.head()

,ChangeTime,LabUpdate,Inferential_avg,Inferential_med,Ratio_avg,Ratio_med,pH_avg,pH_med,CMFlow_avg,CMFlow_med,error_avg,error_med
0,2025-10-16 03:02:30,68,"52,716789","51,08698835","0,380589473","0,380293399","9,113029238","9,113762856","52,38471108","51,07588959","-15,283211","-16,91301165"
1,2025-10-16 06:33:30,60,"62,41755307","63,74654023","0,35585871","0,356621683","9,092202058","9,092871666","62,5942022","64,00079346","2,417553072","3,746540225"
2,2025-10-16 08:32:30,31,"44,39371878","46,67294865","0,342781166","0,342676342","9,090918157","9,092871666","45,91751767","46,83626556","13,39371878","15,67294865"
3,2025-10-16 10:35:40,32,"23,31702046","23,99194305","0,357974786","0,357905269","9,116514277","9,113762856","24,13672841","24,36791992","-8,682979535","-8,008056952"
4,2025-10-16 12:45:30,31,"20,6122777","21,00740895","0,3405839","0,338620573","9,017560911","9,018521309","21,07282445","21,40418625","-10,3877223","-9,992591051"

In [30]:
dataset = dataset.replace(',', '.', regex=True)
dataset = dataset.apply(pd.to_numeric, errors='ignore')

/tmp/ipython-input-3462246338.py:2: FutureWarning:

errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead

In [31]:
dataset = dataset.drop(columns=['ChangeTime', 'Inferential_avg', 'Inferential_med', 'Ratio_med','pH_med','CMFlow_avg','CMFlow_med','error_avg','error_med'])
dataset.head()

   LabUpdate  Ratio_avg   pH_avg
0         68   0.380589 9.113029
1         60   0.355859 9.092202
2         31   0.342781 9.090918
3         32   0.357975 9.116514
4         31   0.340584 9.017561

In [32]:
train_dataset = dataset.sample(frac=0.8, random_state=0)
test_dataset = dataset.drop(train_dataset.index)

print(f'train_dataset length: {len(train_dataset)}')
print(f'test_dataset length: {len(test_dataset)}')

train_dataset length: 53
test_dataset length: 13

In [33]:
train_dataset.head()

    LabUpdate  Ratio_avg   pH_avg
45         24   0.353721 8.939285
28         34   0.369435 9.086791
29         47   0.365395 9.103895
55         36   0.361612 8.797188
63         51   0.387047 8.796699

In [34]:
test_dataset.head()

    LabUpdate  Ratio_avg   pH_avg
0          68   0.380589 9.113029
3          32   0.357975 9.116514
9          30   0.392138 9.099190
19         48   0.390975 8.989384
21         45   0.400103 8.990417

In [35]:
%tensorflow_version 2.x
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

np.set_printoptions(precision=12, suppress=True, linewidth=150)
pd.options.display.float_format = '{:.6f}'.format
tf.__version__
px.scatter_matrix(train_dataset, dimensions=['LabUpdate', 'Ratio_avg', 'pH_avg'], color='LabUpdate', height=700)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.

In [36]:
train_stats = train_dataset.describe()
train_stats.pop('LabUpdate')
train_stats = train_stats.transpose()
train_stats

,count,mean,std,min,25%,50%,75%,max
Ratio_avg,53.000000,0.368652,0.021684,0.306806,0.355859,0.365015,0.378592,0.438227
pH_avg,53.000000,8.974215,0.121867,8.596300,8.868478,9.024020,9.075794,9.108848

In [37]:
train_labels = train_dataset.pop('LabUpdate')
test_labels = test_dataset.pop('LabUpdate')

In [38]:
def norm(x):
    return (x - train_stats['mean']) / train_stats['std']

In [39]:
normed_train_data = norm(train_dataset)
normed_test_data = norm(test_dataset)

In [40]:
normed_train_data.isnull().sum()

Ratio_avg    0
pH_avg       0
dtype: int64

In [44]:
normed_test_data = normed_test_data
normed_train_data = normed_train_data

In [45]:
def norm(x):
    return (x - train_stats['mean']) / train_stats['std']

In [46]:
normed_train_data = norm(train_dataset)
normed_test_data = norm(test_dataset)

In [51]:
def build_model():
    model = Sequential()
    model.add(Dense(128, kernel_regularizer='l2', activation='relu', input_shape=[len(train_dataset.keys())]))
    model.add(Dense(164, activation='relu'))
    model.add(Dense(32, activation='relu'))
    model.add(Dense(1))

    model.compile(optimizer='adam',
                  loss='mse',
                  metrics=['mae', 'mse'])
    return model

In [48]:
model = build_model()
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 24)             │            72 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 12)             │           300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           104 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 485 (1.89 KB)

 Trainable params: 485 (1.89 KB)

 Non-trainable params: 0 (0.00 B)

In [52]:
history = model.fit(normed_train_data, train_labels.values, epochs=200, validation_split=0.2, verbose=1, batch_size=32)

Epoch 1/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - loss: 1181.8553 - mae: 33.2803 - mse: 1181.8124 - val_loss: 1921.6492 - val_mae: 42.8079 - val_mse: 1921.6058
Epoch 2/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1184.2950 - mae: 33.2670 - mse: 1184.2516 - val_loss: 1917.3027 - val_mae: 42.7577 - val_mse: 1917.2589
Epoch 3/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1163.1816 - mae: 33.0059 - mse: 1163.1377 - val_loss: 1912.7817 - val_mae: 42.7055 - val_mse: 1912.7375
Epoch 4/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1196.0452 - mae: 33.4409 - mse: 1196.0010 - val_loss: 1908.0675 - val_mae: 42.6510 - val_mse: 1908.0227
Epoch 5/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1169.9813 - mae: 33.0729 - mse: 1169.9365 - val_loss: 1903.2085 - val_mae: 42.5947 - val_mse: 1903.1632
Epoch 6/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 1202.0996 - mae: 33.5150 - mse: 1202.0542 - val_loss: 1898.1968 - val_mae: 42.5366 - val_mse: 1898.1509
Epoch 7/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 1177.7446 - mae: 33.1303 - mse: 1177.6989 - val_loss: 1893.0327 - val_mae: 42.4767 - val_mse: 1892.9865
Epoch 8/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 1193.4319 - mae: 33.3717 - mse: 1193.3856 - val_loss: 1887.6827 - val_mae: 42.4145 - val_mse: 1887.6360
Epoch 9/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1165.0913 - mae: 33.0242 - mse: 1165.0446 - val_loss: 1882.1027 - val_mae: 42.3495 - val_mse: 1882.0552
Epoch 10/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 1147.8822 - mae: 32.7055 - mse: 1147.8347 - val_loss: 1876.2729 - val_mae: 42.2816 - val_mse: 1876.2250
Epoch 11/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 1164.6357 - mae: 32.9197 - mse: 1164.5878 - val_loss: 1870.1731 - val_mae: 42.2104 - val_mse: 1870.1246
Epoch 12/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 1123.9946 - mae: 32.4541 - mse: 1123.9460 - val_loss: 1863.8571 - val_mae: 42.1365 - val_mse: 1863.8079
Epoch 13/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1151.3652 - mae: 32.7565 - mse: 1151.3160 - val_loss: 1857.2759 - val_mae: 42.0595 - val_mse: 1857.2262
Epoch 14/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1128.0731 - mae: 32.4491 - mse: 1128.0233 - val_loss: 1850.4542 - val_mae: 41.9795 - val_mse: 1850.4038
Epoch 15/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 1115.7931 - mae: 32.2649 - mse: 1115.7426 - val_loss: 1843.4374 - val_mae: 41.8971 - val_mse: 1843.3862
Epoch 16/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1126.1814 - mae: 32.3829 - mse: 1126.1302 - val_loss: 1836.1444 - val_mae: 41.8113 - val_mse: 1836.0927
Epoch 17/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1115.2313 - mae: 32.2452 - mse: 1115.1796 - val_loss: 1828.5604 - val_mae: 41.7219 - val_mse: 1828.5078
Epoch 18/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1105.0168 - mae: 32.0694 - mse: 1104.9644 - val_loss: 1820.6661 - val_mae: 41.6286 - val_mse: 1820.6129
Epoch 19/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 1068.9910 - mae: 31.5760 - mse: 1068.9376 - val_loss: 1812.4803 - val_mae: 41.5317 - val_mse: 1812.4263
Epoch 20/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1103.2463 - mae: 32.0038 - mse: 1103.1923 - val_loss: 1803.9767 - val_mae: 41.4308 - val_mse: 1803.9220
Epoch 21/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1080.4381 - mae: 31.6447 - mse: 1080.3832 - val_loss: 1795.2032 - val_mae: 41.3263 - val_mse: 1795.1477
Epoch 22/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1071.5702 - mae: 31.5063 - mse: 1071.5145 - val_loss: 1786.0524 - val_mae: 41.2171 - val_mse: 1785.9960
Epoch 23/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1066.9838 - mae: 31.4129 - mse: 1066.9274 - val_loss: 1776.5542 - val_mae: 41.1034 - val_mse: 1776.4968
Epoch 24/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 1086.1947 - mae: 31.7073 - mse: 1086.1373 - val_loss: 1766.6882 - val_mae: 40.9850 - val_mse: 1766.6301
Epoch 25/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 1043.6547 - mae: 31.1606 - mse: 1043.5966 - val_loss: 1756.5149 - val_mae: 40.8624 - val_mse: 1756.4559
Epoch 26/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 1054.6438 - mae: 31.2781 - mse: 1054.5846 - val_loss: 1745.9370 - val_mae: 40.7346 - val_mse: 1745.8771
Epoch 27/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 1054.7571 - mae: 31.2122 - mse: 1054.6971 - val_loss: 1734.8862 - val_mae: 40.6008 - val_mse: 1734.8254
Epoch 28/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 1030.4454 - mae: 30.8564 - mse: 1030.3846 - val_loss: 1723.3101 - val_mae: 40.4602 - val_mse: 1723.2485
Epoch 29/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 1043.7555 - mae: 30.9999 - mse: 1043.6940 - val_loss: 1711.3374 - val_mae: 40.3140 - val_mse: 1711.2749
Epoch 30/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 1011.0577 - mae: 30.4879 - mse: 1010.9951 - val_loss: 1698.9474 - val_mae: 40.1620 - val_mse: 1698.8839
Epoch 31/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 1044.1493 - mae: 31.0100 - mse: 1044.0857 - val_loss: 1686.1458 - val_mae: 40.0043 - val_mse: 1686.0813
Epoch 32/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 1009.2701 - mae: 30.4999 - mse: 1009.2056 - val_loss: 1672.9771 - val_mae: 39.8414 - val_mse: 1672.9116
Epoch 33/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 979.8044 - mae: 30.0402 - mse: 979.7390 - val_loss: 1659.4778 - val_mae: 39.6736 - val_mse: 1659.4114
Epoch 34/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 987.9000 - mae: 30.0746 - mse: 987.8336 - val_loss: 1645.6027 - val_mae: 39.5003 - val_mse: 1645.5352
Epoch 35/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 968.7457 - mae: 29.8000 - mse: 968.6783 - val_loss: 1631.3461 - val_mae: 39.3214 - val_mse: 1631.2777
Epoch 36/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 941.7772 - mae: 29.3840 - mse: 941.7087 - val_loss: 1616.6144 - val_mae: 39.1356 - val_mse: 1616.5449
Epoch 37/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 963.5134 - mae: 29.6745 - mse: 963.4439 - val_loss: 1601.5780 - val_mae: 38.9449 - val_mse: 1601.5074
Epoch 38/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 943.3689 - mae: 29.2816 - mse: 943.2984 - val_loss: 1586.2152 - val_mae: 38.7491 - val_mse: 1586.1438
Epoch 39/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 945.5045 - mae: 29.3148 - mse: 945.4329 - val_loss: 1570.3237 - val_mae: 38.5454 - val_mse: 1570.2511
Epoch 40/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 889.7181 - mae: 28.3830 - mse: 889.6456 - val_loss: 1553.9309 - val_mae: 38.3341 - val_mse: 1553.8573
Epoch 41/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 932.6636 - mae: 29.1100 - mse: 932.5898 - val_loss: 1537.1030 - val_mae: 38.1158 - val_mse: 1537.0282
Epoch 42/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 894.8199 - mae: 28.4988 - mse: 894.7451 - val_loss: 1519.9862 - val_mae: 37.8923 - val_mse: 1519.9103
Epoch 43/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 891.1920 - mae: 28.3465 - mse: 891.1161 - val_loss: 1502.6163 - val_mae: 37.6641 - val_mse: 1502.5394
Epoch 44/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 870.3127 - mae: 27.9783 - mse: 870.2357 - val_loss: 1484.8239 - val_mae: 37.4287 - val_mse: 1484.7457
Epoch 45/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 851.4440 - mae: 27.7058 - mse: 851.3658 - val_loss: 1466.6327 - val_mae: 37.1863 - val_mse: 1466.5535
Epoch 46/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 853.2780 - mae: 27.6386 - mse: 853.1987 - val_loss: 1448.0107 - val_mae: 36.9363 - val_mse: 1447.9304
Epoch 47/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 814.8945 - mae: 26.9713 - mse: 814.8140 - val_loss: 1429.0360 - val_mae: 36.6797 - val_mse: 1428.9545
Epoch 48/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 837.5770 - mae: 27.3254 - mse: 837.4953 - val_loss: 1409.7153 - val_mae: 36.4164 - val_mse: 1409.6327
Epoch 49/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 796.6695 - mae: 26.6805 - mse: 796.5867 - val_loss: 1390.1362 - val_mae: 36.1474 - val_mse: 1390.0524
Epoch 50/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 764.7560 - mae: 26.0054 - mse: 764.6721 - val_loss: 1370.1647 - val_mae: 35.8707 - val_mse: 1370.0797
Epoch 51/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 767.4287 - mae: 25.9601 - mse: 767.3436 - val_loss: 1349.9257 - val_mae: 35.5880 - val_mse: 1349.8395
Epoch 52/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 765.0500 - mae: 25.9070 - mse: 764.9638 - val_loss: 1329.4135 - val_mae: 35.2990 - val_mse: 1329.3262
Epoch 53/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 728.6218 - mae: 25.1831 - mse: 728.5345 - val_loss: 1308.5240 - val_mae: 35.0020 - val_mse: 1308.4355
Epoch 54/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 679.6136 - mae: 24.3621 - mse: 679.5251 - val_loss: 1287.2880 - val_mae: 34.6974 - val_mse: 1287.1984
Epoch 55/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 713.5661 - mae: 24.9595 - mse: 713.4764 - val_loss: 1265.5767 - val_mae: 34.3830 - val_mse: 1265.4858
Epoch 56/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - loss: 693.3696 - mae: 24.4257 - mse: 693.2787 - val_loss: 1243.7372 - val_mae: 34.0635 - val_mse: 1243.6453
Epoch 57/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 682.7978 - mae: 24.1525 - mse: 682.7057 - val_loss: 1221.7404 - val_mae: 33.7387 - val_mse: 1221.6473
Epoch 58/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 670.6600 - mae: 23.9192 - mse: 670.5670 - val_loss: 1199.4805 - val_mae: 33.4065 - val_mse: 1199.3864
Epoch 59/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 633.3194 - mae: 23.1253 - mse: 633.2251 - val_loss: 1177.1063 - val_mae: 33.0691 - val_mse: 1177.0110
Epoch 60/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 612.5815 - mae: 22.6463 - mse: 612.4861 - val_loss: 1154.4690 - val_mae: 32.7240 - val_mse: 1154.3726
Epoch 61/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 605.3574 - mae: 22.4978 - mse: 605.2608 - val_loss: 1131.6046 - val_mae: 32.3716 - val_mse: 1131.5071
Epoch 62/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 586.2696 - mae: 22.0388 - mse: 586.1720 - val_loss: 1108.5907 - val_mae: 32.0129 - val_mse: 1108.4921
Epoch 63/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 593.6920 - mae: 22.0938 - mse: 593.5933 - val_loss: 1085.3622 - val_mae: 31.6466 - val_mse: 1085.2625
Epoch 64/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 553.0670 - mae: 21.2890 - mse: 552.9672 - val_loss: 1062.1006 - val_mae: 31.2752 - val_mse: 1061.9999
Epoch 65/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 524.3298 - mae: 20.6579 - mse: 524.2290 - val_loss: 1038.5668 - val_mae: 30.8950 - val_mse: 1038.4650
Epoch 66/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 511.9477 - mae: 20.4179 - mse: 511.8458 - val_loss: 1014.8541 - val_mae: 30.5069 - val_mse: 1014.7512
Epoch 67/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 538.4556 - mae: 20.7724 - mse: 538.3527 - val_loss: 991.1397 - val_mae: 30.1133 - val_mse: 991.0359
Epoch 68/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 496.3968 - mae: 19.8207 - mse: 496.2928 - val_loss: 967.5377 - val_mae: 29.7157 - val_mse: 967.4329
Epoch 69/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 474.8578 - mae: 19.2747 - mse: 474.7529 - val_loss: 943.8286 - val_mae: 29.3104 - val_mse: 943.7227
Epoch 70/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 466.5935 - mae: 18.9815 - mse: 466.4876 - val_loss: 920.0998 - val_mae: 28.8989 - val_mse: 919.9930
Epoch 71/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 441.1769 - mae: 18.4482 - mse: 441.0701 - val_loss: 896.4623 - val_mae: 28.4831 - val_mse: 896.3547
Epoch 72/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 437.0606 - mae: 18.4761 - mse: 436.9528 - val_loss: 873.0144 - val_mae: 28.0644 - val_mse: 872.9057
Epoch 73/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 426.4491 - mae: 17.9443 - mse: 426.3404 - val_loss: 849.7847 - val_mae: 27.6427 - val_mse: 849.6752
Epoch 74/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 409.0258 - mae: 17.6739 - mse: 408.9162 - val_loss: 826.6196 - val_mae: 27.2150 - val_mse: 826.5092
Epoch 75/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 400.0805 - mae: 17.2798 - mse: 399.9700 - val_loss: 803.6633 - val_mae: 26.7840 - val_mse: 803.5520
Epoch 76/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step - loss: 400.1417 - mae: 17.3617 - mse: 400.0303 - val_loss: 781.0875 - val_mae: 26.3533 - val_mse: 780.9753
Epoch 77/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 394.5974 - mae: 17.3328 - mse: 394.4852 - val_loss: 759.2859 - val_mae: 25.9304 - val_mse: 759.1729
Epoch 78/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 338.3055 - mae: 15.7952 - mse: 338.1925 - val_loss: 738.2672 - val_mae: 25.5167 - val_mse: 738.1534
Epoch 79/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 342.0282 - mae: 15.7634 - mse: 341.9143 - val_loss: 717.1127 - val_mae: 25.0937 - val_mse: 716.9982
Epoch 80/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - loss: 337.7540 - mae: 15.7187 - mse: 337.6394 - val_loss: 696.0692 - val_mae: 24.6651 - val_mse: 695.9540
Epoch 81/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - loss: 330.6986 - mae: 15.5414 - mse: 330.5833 - val_loss: 675.4756 - val_mae: 24.2376 - val_mse: 675.3596
Epoch 82/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - loss: 330.2989 - mae: 15.5636 - mse: 330.1829 - val_loss: 655.6989 - val_mae: 23.8206 - val_mse: 655.5823
Epoch 83/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step - loss: 282.1660 - mae: 14.1650 - mse: 282.0494 - val_loss: 636.3426 - val_mae: 23.4058 - val_mse: 636.2254
Epoch 84/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 291.4605 - mae: 14.4603 - mse: 291.3433 - val_loss: 617.0876 - val_mae: 22.9865 - val_mse: 616.9698
Epoch 85/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 280.3881 - mae: 13.9974 - mse: 280.2702 - val_loss: 598.3282 - val_mae: 22.5699 - val_mse: 598.2099
Epoch 86/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 260.9537 - mae: 13.5193 - mse: 260.8353 - val_loss: 580.0038 - val_mae: 22.1542 - val_mse: 579.8849
Epoch 87/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 270.4789 - mae: 13.6456 - mse: 270.3600 - val_loss: 562.4016 - val_mae: 21.7479 - val_mse: 562.2823
Epoch 88/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 252.2163 - mae: 13.0087 - mse: 252.0969 - val_loss: 546.0374 - val_mae: 21.3662 - val_mse: 545.9177
Epoch 89/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 234.5726 - mae: 12.5530 - mse: 234.4529 - val_loss: 530.3617 - val_mae: 20.9945 - val_mse: 530.2416
Epoch 90/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 227.4336 - mae: 12.3057 - mse: 227.3136 - val_loss: 514.9606 - val_mae: 20.6221 - val_mse: 514.8402
Epoch 91/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 224.5991 - mae: 12.2092 - mse: 224.4788 - val_loss: 500.1408 - val_mae: 20.2570 - val_mse: 500.0202
Epoch 92/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 212.4884 - mae: 11.7057 - mse: 212.3678 - val_loss: 485.3987 - val_mae: 19.8854 - val_mse: 485.2778
Epoch 93/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 211.5090 - mae: 11.7157 - mse: 211.3881 - val_loss: 471.0743 - val_mae: 19.5164 - val_mse: 470.9532
Epoch 94/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 191.4738 - mae: 10.9086 - mse: 191.3526 - val_loss: 457.1940 - val_mae: 19.1511 - val_mse: 457.0726
Epoch 95/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 190.2106 - mae: 11.1624 - mse: 190.0892 - val_loss: 443.5025 - val_mae: 18.7841 - val_mse: 443.3810
Epoch 96/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 179.3549 - mae: 10.5540 - mse: 179.2334 - val_loss: 430.0502 - val_mae: 18.4165 - val_mse: 429.9284
Epoch 97/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 181.0606 - mae: 10.7191 - mse: 180.9388 - val_loss: 416.9405 - val_mae: 18.0505 - val_mse: 416.8185
Epoch 98/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 177.7152 - mae: 10.5284 - mse: 177.5932 - val_loss: 404.3414 - val_mae: 17.6896 - val_mse: 404.2193
Epoch 99/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 165.0541 - mae: 10.0725 - mse: 164.9319 - val_loss: 392.4754 - val_mae: 17.3422 - val_mse: 392.3531
Epoch 100/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 160.0149 - mae: 9.9139 - mse: 159.8925 - val_loss: 380.9498 - val_mae: 16.9960 - val_mse: 380.8274
Epoch 101/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 162.9111 - mae: 10.1017 - mse: 162.7886 - val_loss: 369.7982 - val_mae: 16.6527 - val_mse: 369.6756
Epoch 102/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 148.7793 - mae: 9.5238 - mse: 148.6567 - val_loss: 359.2382 - val_mae: 16.3208 - val_mse: 359.1155
Epoch 103/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 157.7598 - mae: 9.9886 - mse: 157.6371 - val_loss: 348.9757 - val_mae: 15.9907 - val_mse: 348.8529
Epoch 104/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 143.0408 - mae: 9.3190 - mse: 142.9180 - val_loss: 339.4164 - val_mae: 15.6757 - val_mse: 339.2935
Epoch 105/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 132.1555 - mae: 9.0380 - mse: 132.0327 - val_loss: 330.1093 - val_mae: 15.3625 - val_mse: 329.9863
Epoch 106/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - loss: 138.7740 - mae: 9.2942 - mse: 138.6511 - val_loss: 321.6783 - val_mae: 15.0742 - val_mse: 321.5553
Epoch 107/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 137.0239 - mae: 9.1422 - mse: 136.9009 - val_loss: 314.8848 - val_mae: 14.8403 - val_mse: 314.7619
Epoch 108/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 132.5453 - mae: 9.0300 - mse: 132.4225 - val_loss: 308.7891 - val_mae: 14.6255 - val_mse: 308.6664
Epoch 109/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 132.6626 - mae: 9.0725 - mse: 132.5399 - val_loss: 303.0948 - val_mae: 14.4198 - val_mse: 302.9723
Epoch 110/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 121.9970 - mae: 8.5970 - mse: 121.8745 - val_loss: 297.5533 - val_mae: 14.2179 - val_mse: 297.4309
Epoch 111/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - loss: 117.3211 - mae: 8.4835 - mse: 117.1988 - val_loss: 292.4355 - val_mae: 14.0307 - val_mse: 292.3133
Epoch 112/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 125.4399 - mae: 8.7261 - mse: 125.3178 - val_loss: 287.7100 - val_mae: 13.8554 - val_mse: 287.5880
Epoch 113/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 123.2685 - mae: 8.6710 - mse: 123.1466 - val_loss: 283.4012 - val_mae: 13.6921 - val_mse: 283.2795
Epoch 114/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 116.0330 - mae: 8.3636 - mse: 115.9113 - val_loss: 279.4009 - val_mae: 13.5378 - val_mse: 279.2794
Epoch 115/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 112.6048 - mae: 8.3097 - mse: 112.4833 - val_loss: 275.5193 - val_mae: 13.3842 - val_mse: 275.3979
Epoch 116/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 109.7594 - mae: 8.2249 - mse: 109.6381 - val_loss: 271.9647 - val_mae: 13.2833 - val_mse: 271.8436
Epoch 117/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 107.8942 - mae: 8.1808 - mse: 107.7732 - val_loss: 269.3587 - val_mae: 13.2210 - val_mse: 269.2379
Epoch 118/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - loss: 100.0839 - mae: 7.7889 - mse: 99.9631 - val_loss: 266.8040 - val_mae: 13.1634 - val_mse: 266.6835
Epoch 119/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 95.1280 - mae: 7.6372 - mse: 95.0075 - val_loss: 264.0025 - val_mae: 13.1186 - val_mse: 263.8823
Epoch 120/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 107.3055 - mae: 8.1208 - mse: 107.1853 - val_loss: 261.4077 - val_mae: 13.0778 - val_mse: 261.2878
Epoch 121/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 110.4074 - mae: 8.3073 - mse: 110.2876 - val_loss: 259.7770 - val_mae: 13.0612 - val_mse: 259.6575
Epoch 122/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 106.4352 - mae: 8.2087 - mse: 106.3157 - val_loss: 258.8745 - val_mae: 13.0628 - val_mse: 258.7554
Epoch 123/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 103.4319 - mae: 7.9194 - mse: 103.3127 - val_loss: 258.2867 - val_mae: 13.0723 - val_mse: 258.1678
Epoch 124/200
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 107.5230 - mae: 8.2553 - mse: 107.4042 - val_loss: 257.8660 - val_mae: 13.0832 - val_mse: 257.7475
Epoch 125/200

In [53]:
def plot_hist(history):
    hist = pd.DataFrame(history.history)
    hist['epoch'] = history.epoch
    hist['rmse'] = np.sqrt(hist['mse'])
    hist['val_rmse'] = np.sqrt(hist['val_mse'])

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['mae'], name='mae', mode='markers+lines'))
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['val_mae'], name='val_mae', mode='markers+lines'))
    fig.update_layout(width=1000, height=500, title='MAE vs. VAL_MAE', xaxis_title='Epoki', yaxis_title='Mean Absolute Error', yaxis_type='log')
    fig.show()

    fig = go.Figure()
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['rmse'], name='rmse', mode='markers+lines'))
    fig.add_trace(go.Scatter(x=hist['epoch'], y=hist['val_rmse'], name='val_rmse', mode='markers+lines'))
    fig.update_layout(width=1000, height=500, title='RMSE vs. VAL_RMSE', xaxis_title='Epoki', yaxis_title='Root Mean Squared Error', yaxis_type='log')
    fig.show()

plot_hist(history)

In [54]:
for name, value in zip(model.metrics_names, model.evaluate(normed_test_data, test_labels.values)):
    print(f'{name:8}{value:.4f}')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - loss: 160.2976 - mae: 10.5440 - mse: 160.1947
loss    160.2976
compile_metrics10.5440

In [55]:
test_predictions = model.predict(normed_test_data).flatten()
test_predictions

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step

array([41.23678 , 39.318623, 43.13202 , 32.773335, 36.907715, 31.680445, 33.065987, 29.853462, 25.949   , 29.243433, 29.899124, 28.970678, 39.462044],
      dtype=float32)

In [56]:
pred = pd.DataFrame(test_labels)
pred['predictions'] = test_predictions
pred.head()

    LabUpdate  predictions
0          68    41.236778
3          32    39.318623
9          30    43.132019
19         48    32.773335
21         45    36.907715

In [57]:
fig = px.scatter(pred, 'LabUpdate', 'predictions')
fig.add_trace(go.Scatter(x=[0, 100], y=[0, 100], mode='lines'))
fig.show()

In [59]:
pred.head()

    LabUpdate  predictions
0          68    41.236778
3          32    39.318623
9          30    43.132019
19         48    32.773335
21         45    36.907715

In [60]:
pred['error'] = pred['LabUpdate'] - pred['predictions']
pred.head()

    LabUpdate  predictions      error
0          68    41.236778  26.763222
3          32    39.318623  -7.318623
9          30    43.132019 -13.132019
19         48    32.773335  15.226665
21         45    36.907715   8.092285

In [64]:
px.histogram(pred, 'error', marginal='rug', width=500)